export const providerLogoLoaders = {
  Swapuz: () => require('@assets/images/providers/Swapuz.png'),
  NeroSwap: () => require('@assets/images/providers/NeroSwap.png'),
  LetsExchange: () => require('@assets/images/providers/LetsExchange.png'),
  Swapter: () => require('@assets/images/providers/Swapter.png'),
  Changehero: () => require('@assets/images/providers/Changehero.png'),
  ChangeNow: () => require('@assets/images/providers/ChangeNow.png'),
  StealthEx: () => require('@assets/images/providers/StealthEx.png'),
  Alfacash: () => require('@assets/images/providers/Alfacash.png'),
  LocalMonero: () => require('@assets/images/providers/LocalMonero.png'),
  XChange: () => require('@assets/images/providers/XChange.png'),
  FixedFloat: () => require('@assets/images/providers/FixedFloat.png'),
  Exch: () => require('@assets/images/providers/Exch.png'),
  Exolix: () => require('@assets/images/providers/Exolix.png'),
  Godex: () => require('@assets/images/providers/Godex.png'),
};

export const providerSquareLogoLoaders = {
  Swapuz: () => require('@assets/images/providers/square/Swapuz.png'),
  NeroSwap: () => require('@assets/images/providers/square/NeroSwap.png'),
  LetsExchange: () => require('@assets/images/providers/square/LetsExchange.png'),
  Swapter: () => require('@assets/images/providers/square/Swapter.png'),
  Changehero: () => require('@assets/images/providers/square/Changehero.png'),
  ChangeNow: () => require('@assets/images/providers/square/ChangeNow.png'),
  StealthEx: () => require('@assets/images/providers/square/StealthEx.png'),
  Alfacash: () => require('@assets/images/providers/square/Alfacash.png'),
  LocalMonero: () => require('@assets/images/providers/square/LocalMonero.png'),
  XChange: () => require('@assets/images/providers/square/XChange.png'),
  FixedFloat: () => require('@assets/images/providers/square/FixedFloat.png'),
  Exch: () => require('@assets/images/providers/square/Exch.png'),
  Exolix: () => require('@assets/images/providers/square/Exolix.png'),
  Godex: () => require('@assets/images/providers/square/Godex.png'),
};
